-- ═══════════════════════════════════════════════════════════════════
--  SI-PINTAR SD v1 — DATA AWAL
--  Jalankan KEDUA (setelah 01-schema.sql) di Supabase → SQL Editor → Run
--  Membuat: sekolah Demo (lengkap dengan data contoh) + SDN 001 Balsel (kosong)
--  Tanggal peminjaman dibuat relatif terhadap hari ini, jadi demo selalu terlihat segar.
-- ═══════════════════════════════════════════════════════════════════

insert into schools (id, slug, name, short_name, is_demo, max_books, loan_days) values
  (1, 'demo', 'SD Contoh Nusantara (Demo)', 'SD Demo', true, 3, 7),
  (2, 'sdn001balsel', 'SDN 001 Balikpapan Selatan', 'SDN 001 Balsel', false, 3, 7);

insert into admins (school_id, username, password_hash, must_change) values
  (1, 'admin', null, false),   -- demo: admin / admin
  (2, 'admin', null, true);    -- SDN 001: admin / admin, wajib ganti saat pertama login

insert into categories (id, school_id, kode, nama, emoji, color) values
  (1, 1, '01', 'Cerpen', '📖', '#EF4444'),
  (2, 1, '02', 'Pengetahuan', '🔬', '#0EA5E9'),
  (3, 1, '03', 'Fiksi', '✨', '#8B5CF6'),
  (4, 1, '04', 'Komik', '💥', '#F97316'),
  (5, 1, '05', 'Pelajaran', '✏️', '#10B981'),
  (6, 1, '06', 'Cerita Rakyat', '🏛️', '#D97706'),
  (7, 1, '07', 'Agama', '🌙', '#0D9488'),
  (8, 1, '08', 'Hobi', '🎨', '#EC4899'),
  (9, 2, '01', 'Cerpen', '📖', '#EF4444'),
  (10, 2, '02', 'Pengetahuan', '🔬', '#0EA5E9'),
  (11, 2, '03', 'Fiksi', '✨', '#8B5CF6'),
  (12, 2, '04', 'Komik', '💥', '#F97316'),
  (13, 2, '05', 'Pelajaran', '✏️', '#10B981'),
  (14, 2, '06', 'Cerita Rakyat', '🏛️', '#D97706'),
  (15, 2, '07', 'Agama', '🌙', '#0D9488'),
  (16, 2, '08', 'Hobi', '🎨', '#EC4899');

insert into shelves (id, school_id, kode, nama) values
  (1, 1, 'A', 'Rak A - Kelas Rendah (1-3)'),
  (2, 1, 'B', 'Rak B - Kelas Tinggi (4-6)'),
  (3, 1, 'C', 'Rak C - Referensi'),
  (4, 1, 'D', 'Rak D - Cerita Rakyat'),
  (5, 1, 'E', 'Rak E - Komik & Fiksi'),
  (6, 2, 'A', 'Rak A - Kelas Rendah (1-3)'),
  (7, 2, 'B', 'Rak B - Kelas Tinggi (4-6)'),
  (8, 2, 'C', 'Rak C - Referensi'),
  (9, 2, 'D', 'Rak D - Cerita Rakyat'),
  (10, 2, 'E', 'Rak E - Komik & Fiksi');

insert into books (id, school_id, judul, penulis, penerbit, tahun, isbn, category_id, shelf_id, cover_url, deskripsi) values
  (1, 1, 'Si Kancil dan Buaya', 'Tim Dongeng Nusantara', 'Pustaka Ceria', 2021, NULL, 6, 4, '/covers/demo/buku-01.svg', 'Kancil yang cerdik ingin menyeberang sungai penuh buaya. Dengan akal cerdasnya, ia meminta para buaya berbaris untuk dihitung.'),
  (2, 1, 'Malin Kundang', 'Tim Dongeng Nusantara', 'Pustaka Ceria', 2020, NULL, 6, 4, '/covers/demo/buku-02.svg', 'Kisah anak yang merantau lalu lupa pada ibunya. Cerita rakyat Sumatra Barat tentang pentingnya berbakti kepada orang tua.'),
  (3, 1, 'Timun Mas', 'Tim Dongeng Nusantara', 'Pustaka Ceria', 2022, NULL, 6, 4, '/covers/demo/buku-03.svg', 'Timun Mas berlari dari raksasa dengan bekal ajaib dari seorang pertapa: biji mentimun, jarum, garam, dan terasi.'),
  (4, 1, 'Layang-Layang Merah Dinda', 'Rara Anindita', 'Kancil Kecil', 2023, NULL, 1, 1, '/covers/demo/buku-04.svg', 'Dinda membuat layang-layang sendiri untuk lomba di kampung. Saat talinya putus, ia belajar tentang pantang menyerah.'),
  (5, 1, 'Sepeda Baru Bima', 'Andi Prasetyo', 'Kancil Kecil', 2022, NULL, 1, 1, '/covers/demo/buku-05.svg', 'Bima menabung berbulan-bulan demi sepeda impian. Tapi temannya sedang butuh bantuan, dan Bima harus memilih.'),
  (6, 1, 'Kue Lapis untuk Nenek', 'Sari Wulandari', 'Rumah Dongeng', 2021, NULL, 1, 1, '/covers/demo/buku-06.svg', 'Bersama ibunya, Ayu belajar membuat kue lapis untuk ulang tahun nenek. Lapis demi lapis, penuh kesabaran dan cinta.'),
  (7, 1, 'Petualangan di Pulau Pelangi', 'Kirana Dewi', 'Bintang Kecil', 2023, NULL, 3, 5, '/covers/demo/buku-07.svg', 'Tiga sahabat terdampar di pulau yang warnanya berubah setiap jam. Mereka harus menemukan jalan pulang sebelum senja.'),
  (8, 1, 'Robot Kecil Bernama Tiko', 'Bayu Saputra', 'Bintang Kecil', 2024, NULL, 3, 5, '/covers/demo/buku-08.svg', 'Tiko adalah robot pembersih yang ingin punya teman. Ia menjelajahi kota dan menemukan arti persahabatan.'),
  (9, 1, 'Rahasia Pohon Beringin', 'Kirana Dewi', 'Bintang Kecil', 2022, NULL, 3, 5, '/covers/demo/buku-09.svg', 'Di bawah pohon beringin tua di halaman sekolah, Rani menemukan peta rahasia yang ditulis murid puluhan tahun lalu.'),
  (10, 1, 'Geng Pesut Mahakam', 'Studio Borneo Ceria', 'Komik Kita', 2024, NULL, 4, 5, '/covers/demo/buku-10.svg', 'Pesut-pesut Sungai Mahakam bekerja sama menjaga sungai tetap bersih dari sampah. Komik lucu tentang cinta lingkungan.'),
  (11, 1, 'Si Beruang Madu Penjaga Hutan', 'Studio Borneo Ceria', 'Komik Kita', 2023, NULL, 4, 5, '/covers/demo/buku-11.svg', 'Beruang madu kecil bernama Maru menjaga hutan Kalimantan dari penebang liar bersama teman-teman satwanya.'),
  (12, 1, 'Kapten Kucing Balikpapan', 'Raka Mahendra', 'Komik Kita', 2024, NULL, 4, 5, '/covers/demo/buku-12.svg', 'Kapten Kucing berpatroli di pelabuhan Balikpapan. Setiap hari ada misteri baru yang harus dipecahkan.'),
  (13, 1, 'Mengenal Planet Tata Surya', 'Dr. Laras Pertiwi', 'Sains Anak', 2022, NULL, 2, 3, '/covers/demo/buku-13.svg', 'Ajak anak berkeliling tata surya: dari Merkurius yang panas sampai Neptunus yang dingin, lengkap dengan fakta seru.'),
  (14, 1, 'Ensiklopedia Hewan Kalimantan', 'Tim Sains Anak', 'Sains Anak', 2021, NULL, 2, 3, '/covers/demo/buku-14.svg', 'Kenali orangutan, bekantan, rangkong, dan hewan unik lain dari hutan Kalimantan beserta cara melindunginya.'),
  (15, 1, 'Kenapa Hujan Turun?', 'Dr. Laras Pertiwi', 'Sains Anak', 2023, NULL, 2, 3, '/covers/demo/buku-15.svg', 'Perjalanan setetes air dari laut ke awan lalu kembali ke bumi. Penjelasan siklus air yang mudah dan penuh gambar.'),
  (16, 1, 'Asyik Belajar Perkalian', 'Budi Hartono, S.Pd.', 'Pena Pintar', 2024, NULL, 5, 2, '/covers/demo/buku-16.svg', 'Belajar perkalian 1 sampai 10 lewat permainan, lagu, dan teka-teki. Cocok untuk latihan di rumah.'),
  (17, 1, 'Bahasa Indonesia Ceria Kelas 3', 'Tim Pena Pintar', 'Pena Pintar', 2024, NULL, 5, 2, '/covers/demo/buku-17.svg', 'Latihan membaca, menulis, dan bercerita untuk kelas 3 dengan teks-teks pendek yang dekat dengan kehidupan anak.'),
  (18, 1, 'IPAS Seru Kelas 4', 'Tim Pena Pintar', 'Pena Pintar', 2024, NULL, 5, 2, '/covers/demo/buku-18.svg', 'Percobaan sederhana dan pengamatan lingkungan sekitar untuk memahami materi IPAS kelas 4.'),
  (19, 1, 'Kisah Teladan Para Nabi', 'Ust. Hasan Basri', 'Cahaya Iman', 2020, NULL, 7, 3, '/covers/demo/buku-19.svg', 'Kumpulan kisah teladan para nabi yang ditulis dengan bahasa sederhana untuk anak sekolah dasar.'),
  (20, 1, 'Doa Sehari-hari Anak', 'Ust. Hasan Basri', 'Cahaya Iman', 2021, NULL, 7, 3, '/covers/demo/buku-20.svg', 'Doa-doa pendek untuk kegiatan sehari-hari, dari bangun tidur sampai belajar, lengkap dengan artinya.'),
  (21, 1, 'Indahnya Berbagi', 'Nur Aisyah', 'Cahaya Iman', 2022, NULL, 7, 1, '/covers/demo/buku-21.svg', 'Cerita-cerita pendek tentang anak-anak yang belajar berbagi dengan teman, tetangga, dan sesama.'),
  (22, 1, 'Origami Hewan Lucu', 'Mei Lestari', 'Kreasi Anak', 2023, NULL, 8, 3, '/covers/demo/buku-22.svg', 'Langkah demi langkah melipat kertas menjadi burung, katak, kucing, dan hewan lucu lainnya.'),
  (23, 1, 'Menggambar Itu Mudah', 'Dimas Aryo', 'Kreasi Anak', 2022, NULL, 8, 3, '/covers/demo/buku-23.svg', 'Mulai dari bentuk dasar, anak diajak menggambar hewan, rumah, dan pemandangan dengan percaya diri.'),
  (24, 1, 'Berkebun di Rumah', 'Mei Lestari', 'Kreasi Anak', 2024, NULL, 8, 3, '/covers/demo/buku-24.svg', 'Menanam cabai, tomat, dan kangkung di pot kecil. Panduan berkebun sederhana untuk anak dan keluarga.');

-- Login demo siswa & orang tua: NISN 0012345678 (Arga Pramudita, 2A), PIN 123456
insert into students (id, school_id, nisn, nama, kelas) values
  (1, 1, '0012345678', 'Arga Pramudita', '2A'),
  (2, 1, '0076319440', 'Aisyah Ramadhani', '2A'),
  (3, 1, '0087606724', 'Citra Lestari', '2A'),
  (4, 1, '0073492534', 'Elina Wulandari', '2A'),
  (5, 1, '0038629622', 'Farhan Hidayat', '2A'),
  (6, 1, '0080254647', 'Gita Permata', '2A'),
  (7, 1, '0091368913', 'Hana Safitri', '2A'),
  (8, 1, '0022727021', 'Ilham Ramadhan', '2A'),
  (9, 1, '0052958034', 'Jihan Aulia', '2A'),
  (10, 1, '0025241063', 'Kevin Saputra', '2A'),
  (11, 1, '0023827228', 'Laras Ayuningtyas', '2A'),
  (12, 1, '0091968962', 'Muhammad Rizky', '2A'),
  (13, 1, '0065041488', 'Budi Santoso', '2B'),
  (14, 1, '0082553356', 'Dimas Prasetyo', '2B'),
  (15, 1, '0067400551', 'Nadia Putri', '2B'),
  (16, 1, '0012770964', 'Oktaviani Sari', '2B'),
  (17, 1, '0056801892', 'Putra Mahesa', '2B'),
  (18, 1, '0052929460', 'Qonita Zahra', '2B'),
  (19, 1, '0095871549', 'Reza Firmansyah', '2B'),
  (20, 1, '0079416933', 'Salsabila Nur', '2B'),
  (21, 1, '0091409628', 'Tegar Wicaksono', '4A'),
  (22, 1, '0072251077', 'Umi Kalsum', '4A'),
  (23, 1, '0078080383', 'Vina Maharani', '4A'),
  (24, 1, '0057449013', 'Wahyu Nugroho', '4A'),
  (25, 1, '0080267028', 'Yusuf Alfarizi', '4A'),
  (26, 1, '0025067759', 'Zahra Amelia', '4A'),
  (27, 1, '0091603570', 'Adit Kurniawan', '4A'),
  (28, 1, '0085848252', 'Bella Anggraini', '4A'),
  (29, 1, '0037708947', 'Cahyo Pamungkas', '4A'),
  (30, 1, '0083257405', 'Dewi Kartika', '4A');

-- Kode eksemplar demo: DEMO-0001 s.d. DEMO-0054 (ketik manual untuk mencoba scan)
insert into book_copies (id, school_id, book_id, qr_code, kondisi, status) values
  (1, 1, 1, 'DEMO-0001', 'baik', 'hilang'),
  (2, 1, 1, 'DEMO-0002', 'baik', 'tersedia'),
  (3, 1, 1, 'DEMO-0003', 'baik', 'tersedia'),
  (4, 1, 2, 'DEMO-0004', 'baik', 'dipinjam'),
  (5, 1, 2, 'DEMO-0005', 'baik', 'tersedia'),
  (6, 1, 2, 'DEMO-0006', 'baik', 'tersedia'),
  (7, 1, 3, 'DEMO-0007', 'baik', 'dipinjam'),
  (8, 1, 3, 'DEMO-0008', 'baik', 'dipinjam'),
  (9, 1, 3, 'DEMO-0009', 'baik', 'tersedia'),
  (10, 1, 4, 'DEMO-0010', 'rusak_ringan', 'dipinjam'),
  (11, 1, 4, 'DEMO-0011', 'baik', 'tersedia'),
  (12, 1, 5, 'DEMO-0012', 'baik', 'tersedia'),
  (13, 1, 5, 'DEMO-0013', 'baik', 'tersedia'),
  (14, 1, 6, 'DEMO-0014', 'baik', 'tersedia'),
  (15, 1, 6, 'DEMO-0015', 'baik', 'tersedia'),
  (16, 1, 7, 'DEMO-0016', 'baik', 'dipinjam'),
  (17, 1, 7, 'DEMO-0017', 'baik', 'dipinjam'),
  (18, 1, 8, 'DEMO-0018', 'baik', 'dipinjam'),
  (19, 1, 8, 'DEMO-0019', 'baik', 'tersedia'),
  (20, 1, 9, 'DEMO-0020', 'baik', 'tersedia'),
  (21, 1, 9, 'DEMO-0021', 'baik', 'tersedia'),
  (22, 1, 10, 'DEMO-0022', 'baik', 'dipinjam'),
  (23, 1, 10, 'DEMO-0023', 'rusak_ringan', 'tersedia'),
  (24, 1, 10, 'DEMO-0024', 'baik', 'tersedia'),
  (25, 1, 11, 'DEMO-0025', 'rusak_ringan', 'dipinjam'),
  (26, 1, 11, 'DEMO-0026', 'baik', 'tersedia'),
  (27, 1, 12, 'DEMO-0027', 'baik', 'tersedia'),
  (28, 1, 12, 'DEMO-0028', 'baik', 'tersedia'),
  (29, 1, 13, 'DEMO-0029', 'rusak_ringan', 'tersedia'),
  (30, 1, 13, 'DEMO-0030', 'baik', 'dipinjam'),
  (31, 1, 13, 'DEMO-0031', 'baik', 'tersedia'),
  (32, 1, 14, 'DEMO-0032', 'baik', 'dipinjam'),
  (33, 1, 14, 'DEMO-0033', 'baik', 'dipinjam'),
  (34, 1, 15, 'DEMO-0034', 'baik', 'dipinjam'),
  (35, 1, 15, 'DEMO-0035', 'baik', 'dipinjam'),
  (36, 1, 16, 'DEMO-0036', 'rusak_ringan', 'dipinjam'),
  (37, 1, 16, 'DEMO-0037', 'baik', 'tersedia'),
  (38, 1, 16, 'DEMO-0038', 'baik', 'tersedia'),
  (39, 1, 17, 'DEMO-0039', 'rusak_ringan', 'dipinjam'),
  (40, 1, 17, 'DEMO-0040', 'baik', 'dipinjam'),
  (41, 1, 18, 'DEMO-0041', 'rusak_ringan', 'dipinjam'),
  (42, 1, 18, 'DEMO-0042', 'baik', 'tersedia'),
  (43, 1, 19, 'DEMO-0043', 'baik', 'tersedia'),
  (44, 1, 19, 'DEMO-0044', 'baik', 'tersedia'),
  (45, 1, 20, 'DEMO-0045', 'baik', 'dipinjam'),
  (46, 1, 20, 'DEMO-0046', 'baik', 'tersedia'),
  (47, 1, 21, 'DEMO-0047', 'baik', 'dipinjam'),
  (48, 1, 21, 'DEMO-0048', 'baik', 'dipinjam'),
  (49, 1, 22, 'DEMO-0049', 'baik', 'dipinjam'),
  (50, 1, 22, 'DEMO-0050', 'baik', 'dipinjam'),
  (51, 1, 23, 'DEMO-0051', 'rusak_ringan', 'tersedia'),
  (52, 1, 23, 'DEMO-0052', 'baik', 'tersedia'),
  (53, 1, 24, 'DEMO-0053', 'baik', 'tersedia'),
  (54, 1, 24, 'DEMO-0054', 'baik', 'dipinjam');

insert into loans (id, school_id, copy_id, book_id, student_id, recorded_by, borrowed_at, due_date, returned_at, return_condition, status) values
  (1, 1, 25, 11, 1, 'siswa', now() - interval '38 days', ((now() - interval '38 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '32 days', 'baik', 'kembali'),
  (2, 1, 41, 18, 1, 'siswa', now() - interval '32 days', ((now() - interval '32 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '26 days', 'rusak_ringan', 'kembali'),
  (3, 1, 27, 12, 1, 'siswa', now() - interval '31 days', ((now() - interval '31 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '29 days', 'baik', 'kembali'),
  (4, 1, 47, 21, 1, 'siswa', now() - interval '29 days', ((now() - interval '29 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '26 days', 'baik', 'kembali'),
  (5, 1, 53, 24, 1, 'siswa', now() - interval '23 days', ((now() - interval '23 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '20 days', 'baik', 'kembali'),
  (6, 1, 22, 10, 1, 'guru', now() - interval '20 days', ((now() - interval '20 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '18 days', 'baik', 'kembali'),
  (7, 1, 4, 2, 1, 'guru', now() - interval '14 days', ((now() - interval '14 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '9 days', 'baik', 'kembali'),
  (8, 1, 41, 18, 1, 'guru', now() - interval '13 days', ((now() - interval '13 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '7 days', 'baik', 'kembali'),
  (9, 1, 53, 24, 1, 'guru', now() - interval '7 days', ((now() - interval '7 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '1 days', 'baik', 'kembali'),
  (10, 1, 39, 17, 1, 'guru', now() - interval '1 days', ((now() - interval '1 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (11, 1, 1, 1, 2, 'guru', now() - interval '34 days', ((now() - interval '34 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'hilang'),
  (12, 1, 7, 3, 2, 'guru', now() - interval '33 days', ((now() - interval '33 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '29 days', 'baik', 'kembali'),
  (13, 1, 4, 2, 2, 'siswa', now() - interval '29 days', ((now() - interval '29 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '25 days', 'baik', 'kembali'),
  (14, 1, 43, 19, 2, 'guru', now() - interval '28 days', ((now() - interval '28 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '25 days', 'baik', 'kembali'),
  (15, 1, 23, 10, 2, 'guru', now() - interval '27 days', ((now() - interval '27 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '15 days', 'rusak_ringan', 'kembali'),
  (16, 1, 18, 8, 2, 'siswa', now() - interval '20 days', ((now() - interval '20 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '13 days', 'baik', 'kembali'),
  (17, 1, 1, 1, 2, 'guru', now() - interval '19 days', ((now() - interval '19 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '18 days', 'baik', 'kembali'),
  (18, 1, 32, 14, 2, 'guru', now() - interval '18 days', ((now() - interval '18 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '15 days', 'baik', 'kembali'),
  (19, 1, 7, 3, 2, 'guru', now() - interval '16 days', ((now() - interval '16 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '7 days', 'baik', 'kembali'),
  (20, 1, 25, 11, 2, 'guru', now() - interval '15 days', ((now() - interval '15 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '8 days', 'rusak_ringan', 'kembali'),
  (21, 1, 18, 8, 2, 'siswa', now() - interval '12 days', ((now() - interval '12 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '9 days', 'baik', 'kembali'),
  (22, 1, 49, 22, 2, 'guru', now() - interval '10 days', ((now() - interval '10 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '5 days', 'baik', 'kembali'),
  (23, 1, 47, 21, 3, 'guru', now() - interval '38 days', ((now() - interval '38 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '31 days', 'baik', 'kembali'),
  (24, 1, 39, 17, 3, 'guru', now() - interval '31 days', ((now() - interval '31 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '24 days', 'baik', 'kembali'),
  (25, 1, 20, 9, 3, 'guru', now() - interval '13 days', ((now() - interval '13 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '3 days', 'baik', 'kembali'),
  (26, 1, 49, 22, 3, 'siswa', now() - interval '3 days', ((now() - interval '3 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (27, 1, 49, 22, 4, 'guru', now() - interval '16 days', ((now() - interval '16 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '12 days', 'baik', 'kembali'),
  (28, 1, 8, 3, 4, 'guru', now() - interval '10 days', ((now() - interval '10 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '6 days', 'baik', 'kembali'),
  (29, 1, 34, 15, 4, 'siswa', now() - interval '1 days', ((now() - interval '1 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (30, 1, 25, 11, 5, 'guru', now() - interval '31 days', ((now() - interval '31 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '25 days', 'rusak_ringan', 'kembali'),
  (31, 1, 20, 9, 5, 'siswa', now() - interval '25 days', ((now() - interval '25 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '24 days', 'baik', 'kembali'),
  (32, 1, 50, 22, 5, 'guru', now() - interval '3 days', ((now() - interval '3 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (33, 1, 27, 12, 6, 'siswa', now() - interval '37 days', ((now() - interval '37 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '32 days', 'baik', 'kembali'),
  (34, 1, 32, 14, 6, 'siswa', now() - interval '36 days', ((now() - interval '36 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '32 days', 'baik', 'kembali'),
  (35, 1, 43, 19, 6, 'siswa', now() - interval '20 days', ((now() - interval '20 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '18 days', 'baik', 'kembali'),
  (36, 1, 45, 20, 6, 'guru', now() - interval '10 days', ((now() - interval '10 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '5 days', 'baik', 'kembali'),
  (37, 1, 27, 12, 6, 'guru', now() - interval '8 days', ((now() - interval '8 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '7 days', 'baik', 'kembali'),
  (38, 1, 40, 17, 6, 'siswa', now() - interval '4 days', ((now() - interval '4 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (39, 1, 54, 24, 6, 'siswa', now() - interval '3 days', ((now() - interval '3 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (40, 1, 47, 21, 6, 'guru', now() - interval '2 days', ((now() - interval '2 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (41, 1, 26, 11, 7, 'guru', now() - interval '37 days', ((now() - interval '37 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '35 days', 'baik', 'kembali'),
  (42, 1, 32, 14, 7, 'guru', now() - interval '23 days', ((now() - interval '23 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '20 days', 'baik', 'kembali'),
  (43, 1, 20, 9, 7, 'guru', now() - interval '2 days', ((now() - interval '2 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '0 days', 'baik', 'kembali'),
  (44, 1, 29, 13, 8, 'guru', now() - interval '33 days', ((now() - interval '33 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '32 days', 'baik', 'kembali'),
  (45, 1, 29, 13, 8, 'guru', now() - interval '30 days', ((now() - interval '30 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '26 days', 'baik', 'kembali'),
  (46, 1, 42, 18, 8, 'guru', now() - interval '26 days', ((now() - interval '26 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '24 days', 'baik', 'kembali'),
  (47, 1, 16, 7, 8, 'guru', now() - interval '22 days', ((now() - interval '22 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '17 days', 'baik', 'kembali'),
  (48, 1, 5, 2, 8, 'guru', now() - interval '19 days', ((now() - interval '19 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '14 days', 'baik', 'kembali'),
  (49, 1, 39, 17, 9, 'guru', now() - interval '39 days', ((now() - interval '39 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '37 days', 'baik', 'kembali'),
  (50, 1, 16, 7, 9, 'guru', now() - interval '30 days', ((now() - interval '30 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '27 days', 'baik', 'kembali'),
  (51, 1, 20, 9, 9, 'guru', now() - interval '29 days', ((now() - interval '29 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '26 days', 'baik', 'kembali'),
  (52, 1, 51, 23, 9, 'guru', now() - interval '28 days', ((now() - interval '28 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '23 days', 'rusak_ringan', 'kembali'),
  (53, 1, 12, 5, 9, 'siswa', now() - interval '25 days', ((now() - interval '25 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '18 days', 'baik', 'kembali'),
  (54, 1, 33, 14, 9, 'siswa', now() - interval '18 days', ((now() - interval '18 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '11 days', 'baik', 'kembali'),
  (55, 1, 1, 1, 9, 'guru', now() - interval '15 days', ((now() - interval '15 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '12 days', 'baik', 'kembali'),
  (56, 1, 39, 17, 9, 'siswa', now() - interval '7 days', ((now() - interval '7 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '4 days', 'baik', 'kembali'),
  (57, 1, 43, 19, 10, 'siswa', now() - interval '40 days', ((now() - interval '40 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '30 days', 'baik', 'kembali'),
  (58, 1, 33, 14, 10, 'siswa', now() - interval '38 days', ((now() - interval '38 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '34 days', 'baik', 'kembali'),
  (59, 1, 45, 20, 10, 'guru', now() - interval '35 days', ((now() - interval '35 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '28 days', 'baik', 'kembali'),
  (60, 1, 17, 7, 10, 'siswa', now() - interval '18 days', ((now() - interval '18 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '12 days', 'baik', 'kembali'),
  (61, 1, 27, 12, 10, 'siswa', now() - interval '17 days', ((now() - interval '17 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '15 days', 'baik', 'kembali'),
  (62, 1, 27, 12, 10, 'guru', now() - interval '12 days', ((now() - interval '12 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '10 days', 'baik', 'kembali'),
  (63, 1, 16, 7, 10, 'siswa', now() - interval '10 days', ((now() - interval '10 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '8 days', 'baik', 'kembali'),
  (64, 1, 40, 17, 10, 'guru', now() - interval '8 days', ((now() - interval '8 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '7 days', 'baik', 'kembali'),
  (65, 1, 36, 16, 11, 'siswa', now() - interval '37 days', ((now() - interval '37 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '34 days', 'baik', 'kembali'),
  (66, 1, 26, 11, 11, 'guru', now() - interval '30 days', ((now() - interval '30 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '24 days', 'baik', 'kembali'),
  (67, 1, 8, 3, 11, 'guru', now() - interval '23 days', ((now() - interval '23 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '16 days', 'baik', 'kembali'),
  (68, 1, 21, 9, 11, 'guru', now() - interval '16 days', ((now() - interval '16 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '10 days', 'baik', 'kembali'),
  (69, 1, 10, 4, 11, 'guru', now() - interval '11 days', ((now() - interval '11 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (70, 1, 44, 19, 12, 'guru', now() - interval '39 days', ((now() - interval '39 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '33 days', 'baik', 'kembali'),
  (71, 1, 54, 24, 12, 'siswa', now() - interval '22 days', ((now() - interval '22 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '17 days', 'baik', 'kembali'),
  (72, 1, 46, 20, 13, 'siswa', now() - interval '36 days', ((now() - interval '36 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '35 days', 'baik', 'kembali'),
  (73, 1, 53, 24, 13, 'guru', now() - interval '34 days', ((now() - interval '34 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '31 days', 'baik', 'kembali'),
  (74, 1, 21, 9, 13, 'siswa', now() - interval '25 days', ((now() - interval '25 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '21 days', 'baik', 'kembali'),
  (75, 1, 29, 13, 13, 'guru', now() - interval '7 days', ((now() - interval '7 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '3 days', 'baik', 'kembali'),
  (76, 1, 7, 3, 14, 'siswa', now() - interval '37 days', ((now() - interval '37 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '36 days', 'baik', 'kembali'),
  (77, 1, 42, 18, 14, 'guru', now() - interval '34 days', ((now() - interval '34 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '30 days', 'baik', 'kembali'),
  (78, 1, 29, 13, 14, 'guru', now() - interval '15 days', ((now() - interval '15 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '11 days', 'baik', 'kembali'),
  (79, 1, 49, 22, 15, 'siswa', now() - interval '39 days', ((now() - interval '39 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '36 days', 'baik', 'kembali'),
  (80, 1, 4, 2, 15, 'guru', now() - interval '37 days', ((now() - interval '37 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '31 days', 'baik', 'kembali'),
  (81, 1, 39, 17, 15, 'guru', now() - interval '23 days', ((now() - interval '23 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '17 days', 'rusak_ringan', 'kembali'),
  (82, 1, 28, 12, 16, 'guru', now() - interval '37 days', ((now() - interval '37 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '32 days', 'baik', 'kembali'),
  (83, 1, 49, 22, 16, 'siswa', now() - interval '34 days', ((now() - interval '34 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '31 days', 'baik', 'kembali'),
  (84, 1, 48, 21, 16, 'siswa', now() - interval '28 days', ((now() - interval '28 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '21 days', 'baik', 'kembali'),
  (85, 1, 36, 16, 16, 'guru', now() - interval '21 days', ((now() - interval '21 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '11 days', 'rusak_ringan', 'kembali'),
  (86, 1, 28, 12, 16, 'guru', now() - interval '15 days', ((now() - interval '15 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '8 days', 'baik', 'kembali'),
  (87, 1, 7, 3, 16, 'guru', now() - interval '4 days', ((now() - interval '4 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (88, 1, 41, 18, 16, 'siswa', now() - interval '2 days', ((now() - interval '2 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (89, 1, 12, 5, 17, 'guru', now() - interval '32 days', ((now() - interval '32 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '28 days', 'baik', 'kembali'),
  (90, 1, 28, 12, 17, 'guru', now() - interval '30 days', ((now() - interval '30 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '27 days', 'baik', 'kembali'),
  (91, 1, 2, 1, 17, 'siswa', now() - interval '27 days', ((now() - interval '27 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '26 days', 'baik', 'kembali'),
  (92, 1, 37, 16, 17, 'guru', now() - interval '20 days', ((now() - interval '20 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '19 days', 'baik', 'kembali'),
  (93, 1, 42, 18, 17, 'guru', now() - interval '14 days', ((now() - interval '14 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '9 days', 'baik', 'kembali'),
  (94, 1, 14, 6, 17, 'guru', now() - interval '12 days', ((now() - interval '12 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '6 days', 'baik', 'kembali'),
  (95, 1, 10, 4, 18, 'guru', now() - interval '40 days', ((now() - interval '40 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '35 days', 'baik', 'kembali'),
  (96, 1, 40, 17, 18, 'siswa', now() - interval '33 days', ((now() - interval '33 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '23 days', 'baik', 'kembali'),
  (97, 1, 19, 8, 18, 'siswa', now() - interval '27 days', ((now() - interval '27 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '19 days', 'baik', 'kembali'),
  (98, 1, 37, 16, 18, 'siswa', now() - interval '17 days', ((now() - interval '17 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '13 days', 'baik', 'kembali'),
  (99, 1, 39, 17, 18, 'guru', now() - interval '16 days', ((now() - interval '16 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '13 days', 'rusak_ringan', 'kembali'),
  (100, 1, 10, 4, 18, 'guru', now() - interval '13 days', ((now() - interval '13 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '12 days', 'rusak_ringan', 'kembali'),
  (101, 1, 42, 18, 18, 'siswa', now() - interval '8 days', ((now() - interval '8 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '4 days', 'baik', 'kembali'),
  (102, 1, 16, 7, 18, 'guru', now() - interval '6 days', ((now() - interval '6 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (103, 1, 1, 1, 19, 'guru', now() - interval '36 days', ((now() - interval '36 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '35 days', 'baik', 'kembali'),
  (104, 1, 14, 6, 19, 'guru', now() - interval '26 days', ((now() - interval '26 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '25 days', 'baik', 'kembali'),
  (105, 1, 24, 10, 19, 'siswa', now() - interval '20 days', ((now() - interval '20 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '15 days', 'baik', 'kembali'),
  (106, 1, 50, 22, 19, 'guru', now() - interval '17 days', ((now() - interval '17 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '13 days', 'baik', 'kembali'),
  (107, 1, 19, 8, 19, 'guru', now() - interval '16 days', ((now() - interval '16 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '15 days', 'baik', 'kembali'),
  (108, 1, 32, 14, 19, 'guru', now() - interval '1 days', ((now() - interval '1 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (109, 1, 16, 7, 20, 'guru', now() - interval '39 days', ((now() - interval '39 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '36 days', 'baik', 'kembali'),
  (110, 1, 22, 10, 20, 'guru', now() - interval '32 days', ((now() - interval '32 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '28 days', 'baik', 'kembali'),
  (111, 1, 52, 23, 20, 'siswa', now() - interval '26 days', ((now() - interval '26 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '19 days', 'baik', 'kembali'),
  (112, 1, 9, 3, 20, 'guru', now() - interval '17 days', ((now() - interval '17 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '15 days', 'baik', 'kembali'),
  (113, 1, 19, 8, 20, 'guru', now() - interval '14 days', ((now() - interval '14 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '3 days', 'baik', 'kembali'),
  (114, 1, 34, 15, 20, 'guru', now() - interval '7 days', ((now() - interval '7 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '4 days', 'baik', 'kembali'),
  (115, 1, 14, 6, 20, 'guru', now() - interval '3 days', ((now() - interval '3 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '2 days', 'baik', 'kembali'),
  (116, 1, 29, 13, 20, 'guru', now() - interval '1 days', ((now() - interval '1 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '0 days', 'rusak_ringan', 'kembali'),
  (117, 1, 36, 16, 21, 'siswa', now() - interval '31 days', ((now() - interval '31 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '27 days', 'baik', 'kembali'),
  (118, 1, 10, 4, 21, 'siswa', now() - interval '30 days', ((now() - interval '30 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '25 days', 'baik', 'kembali'),
  (119, 1, 7, 3, 21, 'guru', now() - interval '27 days', ((now() - interval '27 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '19 days', 'baik', 'kembali'),
  (120, 1, 17, 7, 21, 'guru', now() - interval '9 days', ((now() - interval '9 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (121, 1, 33, 14, 21, 'guru', now() - interval '1 days', ((now() - interval '1 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (122, 1, 48, 21, 22, 'siswa', now() - interval '39 days', ((now() - interval '39 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '36 days', 'baik', 'kembali'),
  (123, 1, 37, 16, 22, 'guru', now() - interval '35 days', ((now() - interval '35 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '28 days', 'baik', 'kembali'),
  (124, 1, 10, 4, 22, 'guru', now() - interval '24 days', ((now() - interval '24 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '14 days', 'baik', 'kembali'),
  (125, 1, 15, 6, 22, 'siswa', now() - interval '13 days', ((now() - interval '13 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '2 days', 'baik', 'kembali'),
  (126, 1, 48, 21, 22, 'siswa', now() - interval '5 days', ((now() - interval '5 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (127, 1, 25, 11, 22, 'guru', now() - interval '4 days', ((now() - interval '4 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (128, 1, 14, 6, 23, 'siswa', now() - interval '38 days', ((now() - interval '38 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '37 days', 'baik', 'kembali'),
  (129, 1, 15, 6, 23, 'guru', now() - interval '37 days', ((now() - interval '37 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '32 days', 'baik', 'kembali'),
  (130, 1, 34, 15, 23, 'guru', now() - interval '34 days', ((now() - interval '34 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '33 days', 'baik', 'kembali'),
  (131, 1, 23, 10, 23, 'guru', now() - interval '32 days', ((now() - interval '32 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '30 days', 'baik', 'kembali'),
  (132, 1, 49, 22, 23, 'guru', now() - interval '29 days', ((now() - interval '29 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '24 days', 'baik', 'kembali'),
  (133, 1, 5, 2, 23, 'guru', now() - interval '25 days', ((now() - interval '25 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '24 days', 'baik', 'kembali'),
  (134, 1, 51, 23, 23, 'guru', now() - interval '19 days', ((now() - interval '19 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '13 days', 'baik', 'kembali'),
  (135, 1, 20, 9, 23, 'guru', now() - interval '18 days', ((now() - interval '18 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '15 days', 'baik', 'kembali'),
  (136, 1, 30, 13, 23, 'guru', now() - interval '1 days', ((now() - interval '1 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (137, 1, 51, 23, 24, 'siswa', now() - interval '36 days', ((now() - interval '36 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '29 days', 'baik', 'kembali'),
  (138, 1, 44, 19, 24, 'guru', now() - interval '32 days', ((now() - interval '32 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '25 days', 'baik', 'kembali'),
  (139, 1, 11, 4, 24, 'siswa', now() - interval '26 days', ((now() - interval '26 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '20 days', 'baik', 'kembali'),
  (140, 1, 13, 5, 24, 'siswa', now() - interval '20 days', ((now() - interval '20 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '17 days', 'baik', 'kembali'),
  (141, 1, 30, 13, 24, 'guru', now() - interval '18 days', ((now() - interval '18 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '9 days', 'baik', 'kembali'),
  (142, 1, 11, 4, 25, 'guru', now() - interval '37 days', ((now() - interval '37 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '35 days', 'baik', 'kembali'),
  (143, 1, 50, 22, 25, 'siswa', now() - interval '9 days', ((now() - interval '9 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '7 days', 'baik', 'kembali'),
  (144, 1, 20, 9, 26, 'guru', now() - interval '40 days', ((now() - interval '40 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '39 days', 'baik', 'kembali'),
  (145, 1, 48, 21, 26, 'siswa', now() - interval '35 days', ((now() - interval '35 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '30 days', 'baik', 'kembali'),
  (146, 1, 4, 2, 26, 'guru', now() - interval '24 days', ((now() - interval '24 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '19 days', 'baik', 'kembali'),
  (147, 1, 45, 20, 26, 'siswa', now() - interval '21 days', ((now() - interval '21 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '18 days', 'baik', 'kembali'),
  (148, 1, 11, 4, 26, 'guru', now() - interval '18 days', ((now() - interval '18 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '13 days', 'baik', 'kembali'),
  (149, 1, 35, 15, 26, 'guru', now() - interval '12 days', ((now() - interval '12 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (150, 1, 4, 2, 26, 'guru', now() - interval '4 days', ((now() - interval '4 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (151, 1, 5, 2, 27, 'guru', now() - interval '36 days', ((now() - interval '36 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '29 days', 'baik', 'kembali'),
  (152, 1, 13, 5, 27, 'guru', now() - interval '31 days', ((now() - interval '31 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '29 days', 'baik', 'kembali'),
  (153, 1, 8, 3, 27, 'guru', now() - interval '15 days', ((now() - interval '15 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '11 days', 'baik', 'kembali'),
  (154, 1, 22, 10, 27, 'guru', now() - interval '11 days', ((now() - interval '11 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (155, 1, 50, 22, 28, 'guru', now() - interval '38 days', ((now() - interval '38 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '31 days', 'baik', 'kembali'),
  (156, 1, 52, 23, 28, 'guru', now() - interval '30 days', ((now() - interval '30 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '28 days', 'baik', 'kembali'),
  (157, 1, 17, 7, 28, 'siswa', now() - interval '25 days', ((now() - interval '25 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '19 days', 'baik', 'kembali'),
  (158, 1, 26, 11, 28, 'guru', now() - interval '19 days', ((now() - interval '19 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '15 days', 'baik', 'kembali'),
  (159, 1, 5, 2, 28, 'guru', now() - interval '12 days', ((now() - interval '12 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '8 days', 'baik', 'kembali'),
  (160, 1, 5, 2, 28, 'siswa', now() - interval '7 days', ((now() - interval '7 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '2 days', 'baik', 'kembali'),
  (161, 1, 26, 11, 28, 'guru', now() - interval '5 days', ((now() - interval '5 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '2 days', 'baik', 'kembali'),
  (162, 1, 36, 16, 28, 'siswa', now() - interval '2 days', ((now() - interval '2 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (163, 1, 3, 1, 29, 'guru', now() - interval '27 days', ((now() - interval '27 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '22 days', 'baik', 'kembali'),
  (164, 1, 34, 15, 29, 'siswa', now() - interval '14 days', ((now() - interval '14 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '13 days', 'baik', 'kembali'),
  (165, 1, 46, 20, 29, 'siswa', now() - interval '8 days', ((now() - interval '8 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '5 days', 'baik', 'kembali'),
  (166, 1, 18, 8, 29, 'guru', now() - interval '6 days', ((now() - interval '6 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (167, 1, 8, 3, 29, 'guru', now() - interval '3 days', ((now() - interval '3 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam'),
  (168, 1, 18, 8, 30, 'guru', now() - interval '30 days', ((now() - interval '30 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '21 days', 'baik', 'kembali'),
  (169, 1, 31, 13, 30, 'guru', now() - interval '27 days', ((now() - interval '27 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '17 days', 'baik', 'kembali'),
  (170, 1, 6, 2, 30, 'siswa', now() - interval '26 days', ((now() - interval '26 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '21 days', 'baik', 'kembali'),
  (171, 1, 47, 21, 30, 'guru', now() - interval '8 days', ((now() - interval '8 days') at time zone 'Asia/Makassar')::date + 7, now() - interval '7 days', 'baik', 'kembali'),
  (172, 1, 45, 20, 30, 'siswa', now() - interval '4 days', ((now() - interval '4 days') at time zone 'Asia/Makassar')::date + 7, NULL, NULL, 'dipinjam');

-- Contoh tantangan buatan guru (berlaku minggu ini)
insert into challenges (school_id, title, action, target, category_id, book_id, points, kelas, start_date, end_date) values
  (1, 'Pekan Dongeng: pinjam 1 buku Cerita Rakyat', 'pinjam', 1, 6, NULL, 20, NULL,
   (now() at time zone 'Asia/Makassar')::date - 2, (now() at time zone 'Asia/Makassar')::date + 5);

-- Kategori & rak untuk SDN 001 sudah dibuat di atas. Buku dan siswa SDN 001 diisi guru lewat aplikasi.

-- Sinkronkan penghitung ID setelah insert dengan ID manual
select setval(pg_get_serial_sequence('schools','id'),     (select max(id) from schools));
select setval(pg_get_serial_sequence('categories','id'),  (select max(id) from categories));
select setval(pg_get_serial_sequence('shelves','id'),     (select max(id) from shelves));
select setval(pg_get_serial_sequence('books','id'),       (select max(id) from books));
select setval(pg_get_serial_sequence('book_copies','id'), (select max(id) from book_copies));
select setval(pg_get_serial_sequence('students','id'),    (select max(id) from students));
select setval(pg_get_serial_sequence('loans','id'),       (select max(id) from loans));

-- ---------- Nomor stiker terpisah dari isi QR ----------
-- Di data contoh, kode DEMO-xxxx menjadi NOMOR STIKER, dan tiap eksemplar mendapat isi QR acak sendiri.
update book_copies
   set label = qr_code,
       qr_code = 'SP' || upper(replace(substr(gen_random_uuid()::text, 1, 13), '-', ''))
 where label is null;

-- ikon kategori demo
update categories set icon = case kode when '01' then 'kategori/cerpen' when '02' then 'kategori/pengetahuan' when '03' then 'kategori/fiksi' when '04' then 'kategori/komik' when '05' then 'kategori/pelajaran' when '06' then 'kategori/cerita-rakyat' when '07' then 'kategori/agama' when '08' then 'kategori/hobi' else 'kategori/semua' end where icon is null;
